Remove non-standard key in desktop file
Causes the following error in flatpak generation:

  error: file contains key "StartupWmClass" in group "Desktop Entry",
  but keys extending the format should start with "X-"